### ISSUE TITLE
Handle filename clashes

### ISSUE THREAD

**Issue by mihkelader** [webcomics/dosage#127]
Dosage doesn't download new comic if there already is one using the same filename(s). Perhaps local files could be stored with unique names (hash of original URL)?

https://www.pidjin.net/2019/02/04/skimpy-armor/ is not downloaded correctly because earlier  https://www.pidjin.net/2018/11/05/face-recognition/ uses the same image file names.

**Comment by TobiX** [comment]
I'm not a fan of unreadable file names 😉 

The module for that comic should probably use an appropriate namer, something like this:
https://github.com/webcomics/dosage/blob/e7410ce26b5f92c1cfffe803c430c0f89c09e92e/dosagelib/plugins/z.py#L78-L80
If you want to take a stab at a fix, please open a pull request - otherwise I will add something later.
