### ISSUE TITLE
Unsounded has random errors

### ISSUE THREAD

**Issue by garbled1** [webcomics/dosage#197]
I looked at the page source and couldn't figure out why.. but..

Unsounded> Retrieving all strips
Unsounded> Saved /comics/download/Unsounded/ch16_53.jpg (275.33KB).
Unsounded> Saved /comics/download/Unsounded/ch16_52.jpg (320.45KB).
Unsounded> Saved /comics/download/Unsounded/ch16_51.jpg (312.59KB).
Unsounded> Saved /comics/download/Unsounded/ch16_50.jpg (311.78KB).
Unsounded> Saved /comics/download/Unsounded/ch16_49.jpg (308.12KB).
Unsounded> Saved /comics/download/Unsounded/ch16_48.jpg (322.55KB).
Unsounded> ERROR: XPath //img[contains(@src, "pageart/")] not found at URL http://www.casualvillain.com/Unsounded/comic/ch16/ch16_47.html.
Unsounded> Saved /comics/download/Unsounded/ch16_46.jpg (315.62KB).
Unsounded> Saved /comics/download/Unsounded/ch16_45.jpg (305.27KB).
Unsounded> Saved /comics/download/Unsounded/ch16_44.jpg (294.23KB).
Unsounded> Saved /comics/download/Unsounded/ch16_43.jpg (301.60KB).
Unsounded> Saved /comics/download/Unsounded/ch16_42.jpg (303.06KB).
Unsounded> Saved /comics/download/Unsounded/ch16_41.jpg (279.53KB).
Unsounded> Saved /comics/download/Unsounded/ch16_40.jpg (327.84KB).
Unsounded> Saved /comics/download/Unsounded/ch16_39.jpg (282.94KB).
Unsounded> Saved /comics/download/Unsounded/ch16_38.jpg (241.86KB).
Unsounded> Saved /comics/download/Unsounded/ch16_37.jpg (281.75KB).
Unsounded> Saved /comics/download/Unsounded/ch16_36.jpg (271.28KB).
Unsounded> ERROR: XPath //img[contains(@src, "pageart/")] not found at URL http://www.casualvillain.com/Unsounded/comic/ch16/ch16_35.html.
Unsounded> Saved /comics/download/Unsounded/ch16_34.jpg (247.80KB).
Unsounded> Saved /comics/download/Unsounded/ch16_33.jpg (275.39KB).
Unsounded> ERROR: XPath //img[contains(@src, "pageart/")] not found at URL http://www.casualvillain.com/Unsounded/comic/ch16/ch16_32.html.
Unsounded> Saved /comics/download/Unsounded/ch16_31.jpg (294.69KB).

**Comment by Ruthalas** [comment]
Unsounded has a great many pages that are composed of multiple images instead of a single comic image.
Often this is to make a border that expands the images, though sometimes it's for gifs that overlay the main image providing motion.

In these cases dosage struggles because the images' locations are non-standard.

Unfortunately, this is likely an issue outside of the scope of dosage to resolve. I recommend making note of the skipped pages and grabbing those yourself. (I have up to ch.15 manually saved- compositing pages that are multi-image, but it took a great deal of work to make it happen.)
