### ISSUE TITLE
robots.txt handling...

### ISSUE THREAD

**Issue by TobiX** [webcomics/dosage#24]
I just fixed a severe bug in robots.txt handling. This made me aware of a big chunk of comics that were already "blocked" by robots.txt (e.g. all of GoComics). I haven't checked all comics yet, but there might be quite a bit more that will now fail...

This brings me to the question: Am I right in the assumption that Dosage is a robot and has to adhere to robots.txt? (I think, yes.) Should we try to get authors/publishers to make exceptions for Dosage?

**Comment by Manabi** [comment]
I've never thought of it as a robot, since most people run it manually.  To me a robot's an automated crawler (like Google/Baidu/etc.)  And I say this as someone who runs an actual robot for an aggregator for a site of mine.  That fully obeys all robots.txt rules and proper robot behavior.  But it also runs fully automated 99% of the time, and is actually a robot.  (The other 1% is that you can have it update a site manually, something that usually only happens when it's first approved.)  Not to mention having a huge chunk of comic stop working would largely defeat the purpose of Dosage.

At best, you won't get them to make exceptions. At worst, they'll start attacking the entire project on DMCA grounds, claiming it violates their copyrights.  There have been other comics-download tools in the past that got attacked.  (I remember one that was simply script code you had to know how to turn into your own script, for downloading Kings Features strips.  Kings Features was not amused and went after the site, they guy had to take the code down.)  Even individual webcomic artists tend to have this "downloading my comics is stealing" mentality.  (Which I've always thought was stupid, I still read their comics manually every day, but use Dosage for keeping a backup.)

Perhaps leave it as default behavior, but add a flag to turn it off, or provide an alternate browser ID for those who run it manually?

**Comment by Null000** [comment]
I agree with Manabi that Dosage doesn't fit the definition of a typical robot as it doesn't wonder around following links. I am in favour of ignoring robots.txt.

Btw GoComics' robots.txt looks like all comments to me.

Btw2 a certain comic has a robots directive to block mozilla browsers. For some reason I find this very funny.

**Comment by TobiX** [comment]
For reference: GoComic's images are all hosted on http://assets.amuniversal.com/ and the [robots.txt](http://assets.amuniversal.com/robots.txt) an that host doesn't allow any "robot"...

**Comment by Manabi** [comment]
That seems much more of a *"Don't crawl our CDN servers"* intention.  Probably wanting to keep the direct images out of things like Google's Image Search.
