### ISSUE TITLE
ComicsKingdom retries error

### ISSUE THREAD

**Issue by scouchman** [webcomics/dosage#294]
Since the beginning of October (10/03/2023) ComicsKindom strips have failed (Using Zits for the example, but all are doing the same):

> 
>$ dosage ComicsKingdom/Zits
> 
> ComicsKingdom/Zits> ERROR: HTTPSConnectionPool(host='comicskingdom.com', port=443): Max retries exceeded with url: /zits (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))
> 

They are also being more aggressive with timeouts and "Excceded your limit" warnings of either seeing too many comics, so not sure if it is related or a symptom, or just them being annoying.

**Comment by TobiX** [comment]
We had the ComicsKingdom certificate pinned before since they were not able to set up their certificates correctly. Recently, they switched certificate providers, so we need to remove the pin.

This was fixed in https://github.com/webcomics/dosage/commit/85127de88d6f64662bb6684a55ae3366ea9d0a8b (see #291) - You might want to install the newest development version (https://github.com/webcomics/dosage?tab=readme-ov-file#installation) to get this fix.
