### ISSUE TITLE
Broken Comics - ComicsKingdom/Mutts

### ISSUE THREAD

**Issue by ladewig** [webcomics/dosage#323]
I was on 3.1.dev150+gf63b899, and starting 5/14, ComicsKingdom/Mutts downloaded Working Cats.

Updated to 3.1.dev158+g76d5180 and now it is erroring out with: 

ComicsKingdom/Mutts> ERROR: XPath //div[d:class("comic-reader-item")][1]//a[contains(@href, "/custom-framed-print/")] not found at URL https://comicskingdom.com/mutts/2024-05-15.

Going to switch to Arcamax/Mutts for now as a workaround.

**Comment by littauer** [comment]
This is not just Mutts, but all of ComicsKingdom.

**Comment by littauer** [comment]
Sorry, I was downlevel but am now at 3.1.dev158+g76d5180.

Much of ComicsKingdom works but Mutts does not. The reason is that Mutts seems to have disabled the "custom-framed-print" option so we can't find the .jpg

Perhaps we can look in <div style="aspect-ratio:wwww / hhhh" ... for "img ... "src=..."url=fubar.jpg

I'm not in a position to fiddle with the source right now. Is somebody else free?

**Comment by TobiX** [comment]
Hmm, so creators can disable the "framed prints" option... Shame, that was the best source for a full-size, unsliced image... I'll try to add a fallback...
